### PR TITLE
[FIX/#65] 디자인 수정 사항 반영

### LINKED ISSUE #65: [FIX] 디자인 수정 사항 반영
## What is this issue? 🛠
디자인 수정 사항을 반영해요
## Progress 🏃‍♀️
- [ ]

### PR DESCRIPTION
**Pull request by nhyeonii**
## Related issue 🛠
- closed #65 

## Work Description ✏️
- 카드 상, 하단의 그라데이션을 적용했어요.
- 엠티뷰 이미지를 추가했어요.

## Screenshot 📸
https://github.com/user-attachments/assets/a016b10e-0b91-409b-afa1-09921d1918e9

## Uncompleted Tasks 😅
- N/A

## To Reviewers 📢
캘린더 뷰 찐 최종 ~~~

## 릴리스 노트

* **새로운 기능**
  * 절차 일정 카드에 애니메이션 효과가 추가되었습니다.
  * 빈 상태 표시가 개선되었습니다.

* **개선 사항**
  * 절차 목록의 레이아웃 구조가 개선되었습니다.
  * UI 시각화 요소가 최적화되었습니다.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: app/src/main/java/com/cherrish/android/presentation/calendar/component/ProcedureScheduleCard.kt [hunk 1]
```diff
@@ -81,83 +72,103 @@ fun ProcedureScheduleCard(
...
+                        items(
+                            items = procedureInfo,
+                            key = { it.procedureId }
+                        ) { procedure ->
+                            ProcedureInfoItem(
+                                procedureName = procedure.procedureName,
+                                procedureDay = procedure.procedureDay,
+                                downTimeDuration = procedure.downTimeDuration,
+                                procedureType = getProcedureType(
+                                    displayMode,
```
Comment (sohee6989) [inline app/src/main/java/com/cherrish/android/presentation/calendar/component/ProcedureScheduleCard.kt]: p3: 파라미터명 써주시면 가독성이 좀 더 좋을 것 같습니다~!!
싫으시면 어쩔수없구요ㅜ

**Review by sohee6989 — COMMENTED** [review]
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!
수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!수고하셨습니다!!!!!!!!!!!!!!!!!!!

**Review by sohee6989 — APPROVED** [review]

File: app/src/main/java/com/cherrish/android/presentation/calendar/component/ProcedureScheduleCard.kt (hunk 1 above)
Comment (nhyeonii) [reply app/src/main/java/com/cherrish/android/presentation/calendar/component/ProcedureScheduleCard.kt]: image
